apiVersion: v1
kind: Service
metadata:
  name: k8s-http-discovery
  namespace: monitoring
  labels:
    app: k8s-http-discovery
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/targets"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: k8s-http-discovery
