{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-http-discovery.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-http-discovery.labels" . | nindent 4 }}
{{- end }}
